# Generated by Django 3.2.16 on 2022-11-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_expertiselevel_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertechstack',
            name='learning_resource',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
